---
# tasks file for journald
- name:     Replace configuration file
  template:
    src:    journald.conf.j2
    dest:   /etc/systemd/journald.conf
  notify:
    - journald restart

- name:     Install systemd-journal-gateway
  yum:
    name:   systemd-journal-gateway
    state:  present

- name:     Create directory for logging
  file:
    path=/var/log/journal
    mode=0755
    owner=root
    group=root
    state=directory
  notify:
  - journald restart

- name:     Copy journal-upload.conf file
  copy:     src=journal-upload.conf dest=/etc/systemd/
- name:     Start journald-upload
  service:  name=systemd-journal-upload state=started enabled=yes
