---
# все машины
- hosts:             all
  become:            yes
  tasks:
  - name:            install epel-release
    yum_repository:  name=epel description=EPEL baseurl=https://download.fedoraproject.org/pub/epel/$releasever/$basearch/ gpgcheck=no
  - name:            install policycoreutils-python
    yum:             name=policycoreutils-python state=present
- hosts:             all, !frontend, !firewall
  become:            yes
  roles:
    - routing
# backup server
- hosts:             backup
  become:            yes
  tasks:
  - name:            Install borg
    yum:             name=borgbackup state=present
  - name:            Add user for backup
    user:
      name:          borguser
      password:      "{{ 'password' | password_hash('sha512') }}"

  - name:            Create directory for store remote backups
    file:            name=/var/backup state=directory owner=borguser group=borguser
  - name:            Enable ssh password login
    lineinfile:
      path:          /etc/ssh/sshd_config
      regexp:        "^PasswordAuthentication no"
      line:          "PasswordAuthentication yes"
  - name:            Restart sshd
    service:         name=sshd state=restarted

# firewall
- hosts:             firewall
  become:            yes
  tasks:
  - name:            Enable routing
    sysctl:
      name:          net.ipv4.ip_forward
      value:         '1'
      sysctl_set:    yes
      state:         present
      reload:        yes
  - name:            Enable masquerade
    iptables:
      table:         nat
      chain:         POSTROUTING
      out_interface: "eth0"
      source:        "192.168.0.0/16"
      jump:          MASQUERADE

  - name:            start firewalld
    service:         name=firewalld state=started enabled=yes

## DMZ zone
  - name:            add DMZ zone (1)
    command:         firewall-cmd --zone=dmz --permanent --add-interface=eth2
  - name:            add DMZ zone (2)
    firewalld:
      zone:          dmz
      masquerade:    "yes"
      permanent:     yes
      immediate:     yes
      state:         enabled
## internal zone
  - name:            add internal zone
    command:         firewall-cmd --zone=internal --permanent --add-interface=eth1

## external zone
  - name:            add external zone (1)
    command:         firewall-cmd --zone=external --permanent --add-interface=eth0
  - name:            add external zone (2)
    firewalld:
      zone:          external
      masquerade:    "yes"
      permanent:     yes
      immediate:     yes
      state:         enabled
  - name:            add external zone (3)
    firewalld:
      zone:          external
      permanent:     yes
      immediate:     yes
      rich_rule:     rule family=ipv4 forward-port port=80 protocol=tcp to-port=80 to-addr=192.168.255.2
      state:         enabled


# log server
- hosts:             log
  become:            yes
  roles:
    - log

# Apache
- hosts:             apache
  become:            yes
  roles:
    - apache


# mysql
- hosts:             mysql
  become:            yes
  roles:
    - mysql

# frontend nginx server in dmz
- hosts:             frontend
  become:            yes
  roles:
    - frontend

- hosts:             all, !backup
  become:            yes
  roles:
    - bkup

- hosts:             all, !log
  become:            yes
  roles:
    - journald

#   настройка только для тестирования
- hosts:             firewall
  become:            yes
  tasks:
  - name:            add internal zone (2)
    firewalld:
      zone:          internal
      masquerade:    "yes"
      permanent:     yes
      immediate:     yes
      state:         enabled
  - name:            add internal zone (3)
    firewalld:
      zone:          internal
      permanent:     yes
      immediate:     yes
      rich_rule:     rule family=ipv4 forward-port port=80 protocol=tcp to-port=80 to-addr=192.168.255.2
      state:         enabled

- hosts:             all
  become:            yes
  tasks:
  - reboot:
